"""update schedule intervals and business timezone

Revision ID: 5d9059bca3ce
Revises: 1734e0b94a6c
Create Date: 2026-06-03 04:23:15.532296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5d9059bca3ce'
down_revision: Union[str, None] = '1734e0b94a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('timezone', sa.String(length=50), server_default='America/Bogota', nullable=False))
    op.add_column('schedules', sa.Column('intervals', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.drop_column('schedules', 'end_time')
    op.drop_column('schedules', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('schedules', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('schedules', 'intervals')
    op.drop_column('businesses', 'timezone')
    # ### end Alembic commands ###
