"""Add service category

Revision ID: 753d2fd051d1
Revises: 5fb3e8d12a6c
Create Date: 2026-05-04 01:33:53.453441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '753d2fd051d1'
down_revision: Union[str, None] = '5fb3e8d12a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_categories_business_id_position', 'service_categories', ['business_id', 'position'], unique=False)
    op.drop_index('uq_businesses_slug_lower', table_name='businesses')
    op.add_column('services', sa.Column('service_category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'services', 'service_categories', ['service_category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'service_category_id')
    op.create_index('uq_businesses_slug_lower', 'businesses', [sa.text('lower(slug::text)')], unique=True)
    op.drop_index('ix_service_categories_business_id_position', table_name='service_categories')
    op.drop_table('service_categories')
    # ### end Alembic commands ###
