"""Add guest customer fields to bookings

Revision ID: 4b26f3094bd3
Revises: 5d9059bca3ce
Create Date: 2026-06-17 07:18:31.036262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b26f3094bd3'
down_revision: Union[str, None] = '5d9059bca3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('customer_name', sa.String(length=150), nullable=True))
    op.add_column('bookings', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column('bookings', sa.Column('customer_phone', sa.String(length=30), nullable=True))
    op.add_column('bookings', sa.Column('customer_whatsapp', sa.String(length=30), nullable=True))
    op.add_column('bookings', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('bookings', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('bookings_user_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_user_id_fkey', 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('bookings', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('bookings', 'notes')
    op.drop_column('bookings', 'customer_whatsapp')
    op.drop_column('bookings', 'customer_phone')
    op.drop_column('bookings', 'customer_email')
    op.drop_column('bookings', 'customer_name')
    # ### end Alembic commands ###
