"""Add branch support

Revision ID: 706e93abc637
Revises: e6300b33030b
Create Date: 2026-06-02 03:19:46.924426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '706e93abc637'
down_revision: Union[str, None] = 'e6300b33030b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
