"""Add Branch and Staff services for v0.4.0 architecture

Revision ID: e6300b33030b
Revises: 753d2fd051d1
Create Date: 2026-06-02 00:35:28.776928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e6300b33030b'
down_revision: Union[str, None] = '753d2fd051d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geocoding_status', sa.String(length=24), nullable=False),
    sa.Column('geocoding_error', sa.Text(), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_geocoding_status'), 'branches', ['geocoding_status'], unique=False)
    
    # --- DATA MIGRATION: Create default branches for existing businesses ---
    op.execute("""
        INSERT INTO branches (
            id, business_id, name, address, city, phone, is_active, 
            latitude, longitude, geocoding_status, geocoding_error, geocoded_at, created_at
        )
        SELECT 
            gen_random_uuid(), id, 'Sede Principal', address, city, phone, true, 
            latitude, longitude, geocoding_status, geocoding_error, geocoded_at, created_at
        FROM businesses
    """)
    # -----------------------------------------------------------------------

    op.create_table('staff_services',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_id', 'service_id')
    )
    
    # Add branch_id as nullable=True first
    op.add_column('bookings', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.add_column('schedules', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.add_column('staff', sa.Column('branch_id', sa.UUID(), nullable=True))

    # --- DATA MIGRATION: Update existing records to point to the new branches ---
    op.execute("""
        UPDATE bookings 
        SET branch_id = (SELECT id FROM branches WHERE branches.business_id = bookings.business_id LIMIT 1)
    """)
    op.execute("""
        UPDATE schedules 
        SET branch_id = (SELECT id FROM branches WHERE branches.business_id = schedules.business_id LIMIT 1)
    """)
    op.execute("""
        UPDATE staff 
        SET branch_id = (SELECT id FROM branches WHERE branches.business_id = staff.business_id LIMIT 1)
    """)
    # -----------------------------------------------------------------------

    # Alter to non-nullable where required
    op.alter_column('bookings', 'branch_id', nullable=False)
    op.alter_column('schedules', 'branch_id', nullable=False)

    op.create_foreign_key(None, 'bookings', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'schedules', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'staff', 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')

    op.drop_index('ix_businesses_geocoding_status', table_name='businesses')
    op.drop_column('businesses', 'longitude')
    op.drop_column('businesses', 'geocoded_at')
    op.drop_column('businesses', 'geocoding_error')
    op.drop_column('businesses', 'latitude')
    op.drop_column('businesses', 'geocoding_status')
    op.drop_column('businesses', 'city')
    op.drop_column('businesses', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_column('staff', 'branch_id')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'branch_id')
    op.add_column('businesses', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('businesses', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('businesses', sa.Column('geocoding_status', sa.VARCHAR(length=24), autoincrement=False, nullable=False))
    op.add_column('businesses', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('geocoding_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('geocoded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index('ix_businesses_geocoding_status', 'businesses', ['geocoding_status'], unique=False)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'branch_id')
    op.drop_table('staff_services')
    op.drop_index(op.f('ix_branches_geocoding_status'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
