"""add is_demo_seed to bookings

Revision ID: 34da078891ad
Revises: 45921232d8c3
Create Date: 2026-07-30 16:48:17.677555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '34da078891ad'
down_revision: Union[str, None] = '45921232d8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('is_demo_seed', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_bookings_is_demo_seed'), 'bookings', ['is_demo_seed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_is_demo_seed'), table_name='bookings')
    op.drop_column('bookings', 'is_demo_seed')
    # ### end Alembic commands ###
