"""add_booking_timestamps

Revision ID: 45921232d8c3
Revises: 832c65105438
Create Date: 2026-07-09 02:19:45.583766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '45921232d8c3'
down_revision: Union[str, None] = '832c65105438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('bookings', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'paid_at')
    op.drop_column('bookings', 'cancelled_at')
    op.drop_column('bookings', 'completed_at')
    op.drop_column('bookings', 'confirmed_at')
    op.drop_column('bookings', 'created_at')
    # ### end Alembic commands ###
