"""add_schedule_blocks_table

Revision ID: 1a2e8ce3964d
Revises: 34da078891ad
Create Date: 2026-08-22 01:39:54.115577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1a2e8ce3964d'
down_revision: Union[str, None] = '34da078891ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_blocks_branch_id'), 'schedule_blocks', ['branch_id'], unique=False)
    op.create_index(op.f('ix_schedule_blocks_business_id'), 'schedule_blocks', ['business_id'], unique=False)
    op.create_index(op.f('ix_schedule_blocks_end_date'), 'schedule_blocks', ['end_date'], unique=False)
    op.create_index(op.f('ix_schedule_blocks_staff_id'), 'schedule_blocks', ['staff_id'], unique=False)
    op.create_index(op.f('ix_schedule_blocks_start_date'), 'schedule_blocks', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_blocks_start_date'), table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_staff_id'), table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_end_date'), table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_business_id'), table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_branch_id'), table_name='schedule_blocks')
    op.drop_table('schedule_blocks')
    # ### end Alembic commands ###
