"""Add whatsapp_phone to branches

Revision ID: 1734e0b94a6c
Revises: 706e93abc637
Create Date: 2026-06-02 05:21:37.143156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1734e0b94a6c'
down_revision: Union[str, None] = '706e93abc637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('whatsapp_phone', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'whatsapp_phone')
    # ### end Alembic commands ###
