"""Add photo_url to staff

Revision ID: 832c65105438
Revises: 4b26f3094bd3
Create Date: 2026-06-17 07:48:06.804039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '832c65105438'
down_revision: Union[str, None] = '4b26f3094bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'photo_url')
    # ### end Alembic commands ###
